apiVersion: v1
kind: Pod
metadata:
  name: no-secrets-as-env-vars-violation
  namespace: dhl-1
spec:
  containers:
  - name: my-container
    image: busybox:latest
    env:
    - name: MY_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: secret-key

---
apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: dhl-1
type: Opaque
data:
  secret-key: c2VjcmV0LXZhbHVl
