apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-with-dhl-team-label
  labels:
    app: nginx
    team: dhl
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80