kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: anupam
  name: namespace-reader-2
  annotations:
    configsync.gke.io/cluster-name-selector: policy-controller-cluster-1
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]