apiVersion: v1
kind: Pod
metadata:
  name: nginx-w-annotations
  namespace: armenia
  annotations:
    configmanagement.gke.io/cluster-selector: selector-for-prod-env
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
