apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: Assign
metadata:
  name: ifnotpresent-pull-image
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  location: "spec.containers[name: *].imagePullPolicy"
  parameters:
    assign:
      value: "IfNotPresent"